FindJob/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using FindJob.Models.Enums;
using FindJob.Models.Helper;
using FindJob.Models.Interfaces.Handler;
using FindJob.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FindJob.Controllers
{
	public class AccountController : Controller
	{
		private readonly IAccountLoginHandler _accountLoginHandler;

		public AccountController(IAccountLoginHandler accountLoginHandler)
		{
			_accountLoginHandler = accountLoginHandler;
		}

		[HttpGet]
		public IActionResult Login()
		{
			return View();
		}

		[HttpGet]
		public IActionResult Register()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Register(RegisterModel registerModel)
		{
			if (!ModelState.IsValid)
				return View("Register");

			var result = await _accountLoginHandler.TryRegister(registerModel);
			if (result.Succeeded)
				return await GetViewByRoleAsync();

			AddErrors(result.Errors);
			return View("Register");
		}

		[HttpPost]
		public async Task<IActionResult> Enter(LoginModel login)
		{
			if (!ModelState.IsValid)
				return View("Login");

			var result = await _accountLoginHandler.TryLogin(login);
			if (result.Succeeded)
				return await GetViewByRoleAsync();

			AddErrors(result.Errors);
			return View("Login");

		}

		private void AddErrors(IEnumerable<string> errors)
		{
			foreach (var error in errors)
			{
				ModelState.AddModelError("", error);
			}
		}

		public async Task<IActionResult> Logout()
		{
			// удаляем аутентификационные куки
			await _accountLoginHandler.LogOutAsync();
			return RedirectToAction(nameof(MainController.StartPage), nameof(MainController).GetNameOfController());
		}

		[HttpGet]
		public IActionResult Remember()
		{			
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Remember(OneEmail oneEmail)
		{
			var result = await _accountLoginHandler.RememberAsync(oneEmail.Email);
			if (result.Succeeded)
				return View(nameof(Login));			
			AddErrors(result.Errors);
			return View();
		}

		public async Task<RedirectToActionResult> GetViewByRoleAsync()
		{
			var role = await _accountLoginHandler.GetRoleAsync();

			if (role == Roles.Worker)
				return RedirectToAction(nameof(WorkerController.Vacancies), nameof(WorkerController).GetNameOfController());

			if (role == Roles.Employer)
				return RedirectToAction(nameof(EmployerController.Account), nameof(EmployerController).GetNameOfController());

			throw new NotSupportedException($"Не реализовано для роли {role}");
		}

		[Authorize]
		public IActionResult Restore()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Restore(RestorePasswordModel resetPasswordModel)
		{
			if (!ModelState.IsValid)
				return View("Restore");
			var result = await _accountLoginHandler.RestoreAsync(resetPasswordModel, HttpContext.User.Identity.Name);
			if (result.Succeeded)
				return await GetViewByRoleAsync();
			AddErrors(result.Errors);
			return await GetAccountViewByRoleAsync();
		}

		public async Task<RedirectToActionResult> GetAccountViewByRoleAsync()
		{
			var role = await _accountLoginHandler.GetRoleAsync();

			if (role == Roles.Worker)
				return RedirectToAction(nameof(WorkerController.Account), nameof(WorkerController).GetNameOfController());

			if (role == Roles.Employer)
				return RedirectToAction(nameof(EmployerController.Account), nameof(EmployerController).GetNameOfController());

			throw new NotSupportedException($"Не реализовано для роли {role}");
		}
	}
}

FindJob/Controllers/EmployerController.cs
using System;
using System.Threading.Tasks;
using FindJob.Models.Enums;
using FindJob.Models.Helper;
using FindJob.Models.Interfaces.Handler;
using FindJob.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FindJob.Controllers
{
	[Authorize(Roles = nameof(Roles.Employer))]
	public class EmployerController : Controller
	{
		private readonly IEmployerHandler _employerHandler;

		public EmployerController(IEmployerHandler employerHandler)
		{
			_employerHandler = employerHandler;
		}
		public IActionResult Create(Guid vacancyId)
		{
			return View(_employerHandler.GetVacancyById(vacancyId));
		}

		[HttpPost]
		public async Task<IActionResult> Save(Vacancy vacancy)
		{
			await _employerHandler.AddToVacancyRepo(vacancy, HttpContext.User.Identity.Name);
			return RedirectToAction(nameof(Vacancies));
		}

		public IActionResult Vacancies()
		{
			return View(_employerHandler.GetUserVacancies(HttpContext.User.Identity.Name));
		}

		public async Task<IActionResult> DeleteAsync(Guid vacancyId)
		{
			await _employerHandler.RemoveVacancy(vacancyId);
			return RedirectToAction(nameof(Vacancies));
		}

		public IActionResult Resumes()
		{
			return View(_employerHandler.GetResumes());
		}

		public IActionResult Account()
		{
			return View();
		}

		public IActionResult Resume(Guid resumeId)
		{
			var resume = _employerHandler.GetResume(resumeId);
			ViewBag.imgSrc = ControllerHelper.GetImageString(resume);
			return View(resume);
		}

		public IActionResult Responses()
		{
			return View(_employerHandler.GetResponses(HttpContext.User.Identity.Name));
		}
	}
}

FindJob/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using FindJob.Models.Enums;
using FindJob.Models.Helper;
using FindJob.Models.Interfaces.Handler;
using FindJob.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FindJob.Controllers
{
	[Authorize(Roles = nameof(Roles.Worker))]
	public class WorkerController : Controller
	{
		private readonly IWorkerHandler _workerHandler;

		public WorkerController(IWorkerHandler workerHandler)
		{
			_workerHandler = workerHandler;
		}
		public IActionResult Create(Guid resumeId)
		{
			var resume = _workerHandler.GetResumeById(resumeId);
			ViewBag.imgSrc = ControllerHelper.GetImageString(resume);
			return View(resume);
		}

		[HttpPost]
		public async Task<IActionResult> Save(Resume resume)
		{			
			await _workerHandler.AddToResumeRepo(resume, HttpContext.User.Identity.Name);
			return RedirectToAction(nameof(Resumes));
		}

		public IActionResult Resumes()
		{
			return View(GetUserResumes());
		}

		public async Task<IActionResult> DeleteAsync(Guid resumeId)
		{
			await _workerHandler.RemoveResume(resumeId);			
			return RedirectToAction(nameof(Resumes));
		}

		public IActionResult Vacancies()
		{
			return View(_workerHandler.GetVacancies());
		}

		public async Task<IActionResult> MakeMainAsync(Guid resumeId)
		{
			await _workerHandler.MakeMainResumeAsync(resumeId, HttpContext.User.Identity.Name);
			return RedirectToAction(nameof(Resumes));
		}

		public async Task<IActionResult> ResponseVacancy(Guid vacancyId)
		{
			await _workerHandler.AddResponseVacancyAsync(vacancyId, HttpContext.User.Identity.Name);
			return RedirectToAction(nameof(Vacancies));
		}

		public IActionResult Responses()
		{
			return View(_workerHandler.GetResponses(HttpContext.User.Identity.Name));
		}

		public IActionResult Vacancy(Guid vacancyId)
		{
			return View(_workerHandler.GetVacancy(vacancyId));
		}

		private IEnumerable<Resume> GetUserResumes()
		{
			return _workerHandler.GetUserResumes(HttpContext.User.Identity.Name);
		}

		public IActionResult Account()
		{
			return View(_workerHandler.GetProfile(HttpContext.User.Identity.Name));
		}

		public IActionResult RedactProfile(Guid id)
		{
			return View(_workerHandler.GetWorkerProfile(id));
		}

		public async Task<IActionResult> SaveProfile(WorkerProfile workerProfile)
		{
			await _workerHandler.SavePorfileAsync(workerProfile);
			return RedirectToAction(nameof(Account));
		}
	}
}

FindJob/Views/Shared/_Account.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

FindJob/Views/Shared/_EmployerLayout.cshtml
<head>
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
</head>
<title>@ViewBag.Title</title>
<body>
    <nav class="navbar navbar navbar-expand-lg navbar-light bg-light" style="background-color: #ffffff;">
        <a class="nav-link" asp-action="Resumes" asp-controller="Employer">Резюме</a>
        <a class="nav-link" asp-action="Vacancies" asp-controller="Employer">Мои вакансии</a>
        <a class="nav-link" asp-action="Create" asp-controller="Employer">Создать вакансию</a>
        <a class="nav-link" asp-action="Account" asp-controller="Employer">Аккаунт</a>
        <a class="nav-link" asp-action="Responses" asp-controller="Employer">Ответы</a>
        <a class="nav-link" asp-action="Logout" asp-controller="Account">Выйти</a>
    </nav>
    @RenderBody()
</body>

FindJob/Views/Shared/_Layout.cshtml
<title>@ViewBag.Title</title>
@RenderBody()

FindJob/Views/Shared/_WorkerLayout.cshtml
<title>@ViewBag.Title</title>
<head>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
</head>
<body>
    <nav class="navbar navbar navbar-expand-lg navbar-light bg-light" style="background-color: #ffffff;">
        <a class="nav-link" asp-action="Vacancies" asp-controller="Worker">Вакансии</a>
        <a class="nav-link" asp-action="Resumes" asp-controller="Worker">Мои резюме</a>
        <a class="nav-link" asp-action="Create" asp-controller="Worker">Создать резюме</a>
        <a class="nav-link" asp-action="Responses" asp-controller="Worker">Ответы</a>
        <a class="nav-link" asp-action="Account" asp-controller="Worker">Аккаунт</a>
        <a class="nav-link" asp-action="Logout" asp-controller="Account">Выйти</a>
    </nav>
    @RenderBody()
</body>